run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive
    - gofmt
    - goimports
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-strings
      - name: indent-error-flow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
